### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Paimon-Kawaii** [PantsuDango/Dango-Translator#102]
#### 使用官网4.3.7的安装包安装并打开后提示升级4.3.9，升级后注册并登陆，软件闪退，日志文件报错如下：
>  [2023-01-01 16:16:32,944][utils\config.py-line:347][ERROR]
Traceback (most recent call last):
  File "utils\config.py", line 344, in readCloudConfigFormLocal
FileNotFoundError: [Errno 2] No such file or directory: './config/cloud_config.json'
> 
>  [2023-01-01 16:16:38,195][translator\sound.py-line:62][ERROR]
Traceback (most recent call last):
  File "translator\sound.py", line 58, in openWebdriver
  File "selenium\webdriver\chrome\webdriver.py", line 76, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
> 
>  [2023-01-01 16:16:38,195][translator\all.py-line:159][ERROR]
Traceback (most recent call last):
  File "translator\all.py", line 155, in openWebdriver
  File "selenium\webdriver\chrome\webdriver.py", line 76, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

#### 尝试重新安装4.3.7，不升级4.3.9,并登陆，软件闪退，日志文件报错如下：
> [2023-01-01 16:18:24,530][utils\config.py-line:22][ERROR]
Traceback (most recent call last):
  File "utils\config.py", line 18, in openConfig
FileNotFoundError: [Errno 2] No such file or directory: './config/config.yaml'
> 
> [2023-01-01 16:19:01,808][utils\config.py-line:341][ERROR]
Traceback (most recent call last):
  File "utils\config.py", line 338, in readCloudConfigFormLocal
FileNotFoundError: [Errno 2] No such file or directory: './config/cloud_config.json'

#### 经过尝试后在4.3.7解决FileNotFound并成功登陆，升级4.3.9登陆后，软件无响应，日志文件报错如下：
> [2023-01-01 16:57:40,989][translator\all.py-line:159][ERROR]
Traceback (most recent call last):
  File "translator\all.py", line 155, in openWebdriver
  File "selenium\webdriver\chrome\webdriver.py", line 76, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

#### 部分Bug原因猜想&建议：
> FileNotFound
> 猜测：根据函数名：`readCloudConfigFormLocal`，猜测功能应该是从本地读取一个云端配置的缓存文件
> 验证：在本地创建对应文件后，并键入`{}`内容，异常消失且成功登陆。
> 能否复现：可以复现
> 建议：在`readCloudConfigFormLocal`函数中添加判断，若文件不存在则创建文件，并写入默认配置

> WebDriverException - 4.3.9无响应问题
> 描述：这个异常本来没事，但是若出现异常问题导致启动失败，会使webdriver进程驻留，且不会自动销毁，导致下次重新启动时软件无响应
> 验证：通过任务管理器结束多余的`chromedriver.exe`与`geckodriver.exe`进程后登陆成功
> 能否复现：可以复现，但仅能通过4.3.7升级4.3.9后才会出现，共复现3次
> 建议：估计是小概率事件，目前我也没定位到哪个环节出现问题，猜测有可能是4.3.7的遗留问题，也许是自动升级结束翻译器进程结束的不够干净？XD。

**Comment by PantsuDango** [comment]
非常感谢您的反馈，我仔细看了该部分的源码。我认为应该不是readCloudConfigFormLocal造成的，能造成软件闪退的错误，是未知的错误，就是不能被try捕捉到的错误，这样的错误出现了但我们没有处理所以造成了崩溃。你在日志文件里看到的错误都是被捕捉了的错误，程序也是正常处理它了，是不会造成崩溃的，应该还有其他原因

**Comment by PantsuDango** [comment]
你好，请问您是否在我的任何一个交流群里？我希望能通过qq和你交流一下，如何复现这个问题，我希望彻底修复它

**Comment by Paimon-Kawaii** [comment]
这个问题我之前猜想的不太一样，在更新4.4.0版本后，这个问题经常出现，我目前还不确定其触发方式，我尽量在这几天试出稳定的复现原因，之后再与您联系

**Comment by Paimon-Kawaii** [comment]
这个问题我之前猜想的不太一样，在更新4.4.0版本后，这个问题经常出现，我目前还不确定其触发方式，我尽量在这几天试出稳定的复现原因，之后再与您联系

**Comment by PantsuDango** [comment]
太感谢了，我也非常想修复这个问题，如果能解决真的是太好了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月4日(星期三) 晚上9:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] Bug report (Issue #102)





 
这个问题我之前猜想的不太一样，在更新4.4.0版本后，这个问题经常出现，我目前还不确定其触发方式，我尽量在这几天试出稳定的复现原因，之后再与您联系

**Comment by Paimon-Kawaii** [comment]
目前已经找到稳定的触发方式，且可以在4.3.7之后的版本复现。
在4.3.7版本时测试出该Bug的复现方式如下：
提前打开Edge浏览器，然后再运行翻译器并登陆，会导致软件闪退；经过验证，在Chrome和FireFox上无此问题。
另外在4.3.9及4.4.0版本发现新的Bug，第一次登陆没有问题，待退出后重新运行并登陆，软件会无响应，并且只有重启电脑才能解决此问题。
另外我已经通过QQ与您反馈相关问题，请您注意查收QQ消息
