### ISSUE TITLE
繁體中文介面下發生的一些語系問題

### ISSUE THREAD

**Issue by WWW5911** [PantsuDango/Dango-Translator#82]
目前使用繁體中文介面，碰上兩個問題

使用自帶之ocr功能時，會發生UnicodeDecodeError
內容如下

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\DangoTranslator\app\ocr\Python\lib\site-packages\qpt\run.py", line 12, in <module>
    module = RunExecutableModule("./")
  File "C:\DangoTranslator\app\ocr\Python\lib\site-packages\qpt\executor.py", line 360, in __init__
    set_default_pip_lib(self.interpreter_path)
  File "C:\DangoTranslator\app\ocr\Python\lib\site-packages\qpt\kernel\tools\interpreter.py", line 229, in set_default_pip_lib
    PIP.pip_main = PIPTerminal(interpreter_path).shell_func()
  File "C:\DangoTranslator\app\ocr\Python\lib\site-packages\qpt\kernel\tools\interpreter.py", line 21, in __init__
    super(PIPTerminal, self).__init__()
  File "C:\DangoTranslator\app\ocr\Python\lib\site-packages\qpt\kernel\tools\terminal.py", line 138, in __init__
    super(PTerminal, self).__init__()
  File "C:\DangoTranslator\app\ocr\Python\lib\site-packages\qpt\kernel\tools\terminal.py", line 92, in __init__
    self.init_terminal()
  File "C:\DangoTranslator\app\ocr\Python\lib\site-packages\qpt\kernel\tools\terminal.py", line 147, in init_terminal
    self._shell_func()(prepare)
  File "C:\DangoTranslator\app\ocr\Python\lib\site-packages\qpt\kernel\tools\terminal.py", line 169, in closure
    callback.handle(self.main_terminal)
  File "C:\DangoTranslator\app\ocr\Python\lib\site-packages\qpt\kernel\tools\terminal.py", line 67, in handle
    msg = line.decode('gbk').strip("b'").strip("\n").strip(SHELL_ACT)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 19: illegal multibyte sequence

由於在60行取得terminal資訊為：`b'Microsoft Windows [\xaa\xa9\xa5\xbb 10.0.19042.631]\r\n'`
應使用big5轉換，得`Microsoft Windows [版本 10.0.19042.631]`
將第67行改為：
            try:
                msg = line.decode('gbk').strip("b'").strip("\n").strip(SHELL_ACT)
            except:
                msg = line.decode('big5').strip("b'").strip("\n").strip(SHELL_ACT)
後能正常運行且terminal無亂碼發生，但不知對於其他的影響，總之能正常使用。

第二個為開啟時跳出「字體文件缺失」的提示
安裝字體後仍會在每次啟動跳出此提示

**Comment by PantsuDango** [comment]
最新版本的本地OCR应该不会再出现此问题，可以尝试更新，详见 [B站动态](https://www.bilibili.com/opus/765552391458127952?spm_id_from=333.999.0.0)
